- src/types.ts
Not entirely sure why, but when trying to build a next project using `b-sdk`, I get errors because of the re-export of types from viem. The types are straightforward, so figure just redefining them is also fine. This ok for you?
> Re-export of viem types causing build errors in consuming project

- src/abi/index.ts
- src/abi/tokenRates.ts
- src/data/enrichers/onChainPoolDataEnricher.ts
- src/sor.ts
- src/utils/constants.ts
- test/gyroEV2Pool.integration.test.ts
- test/lib/testData/gyroETestPool.json
- test/sor.test.ts
I didn't push to the working branch so I don't "polute" it. I'd rather keep things separate until we consider this one ready to go.
I added tokenRates to the pool enricher by using the multicall available on viem and I tried keeping consistency with we already have on the code, but I'm not sure this case should be handled differently.
I tried to keep it flexible, so any pool that provides this type of function could be called (instead of enforcing it to be GyroE v2 pools).
Let me know what you think.
> Add token rates to pool enricher using multicall

- pnpm-lock.yaml
- src/data/enrichers/onChainPoolDataEnricher.ts
- src/entities/pools/stable/stablePool.ts
- test/sor.test.ts
Updating test block number in #73 leads to existing tests failing. For the new block a different swap path is being found. The new CS amp value is such that the loss of accuracy during enrichment leads to errors during future calculations.
* Update block no in test to replicate issue seen in #73 
* Update amp parsing during enrichment
* Update OnChainPoolDataEnricher config in test to load Amp for ComposableStable pools because SG value was incorrect (Maybe this should be a default?)
> fix: keep amp accuracy in enrichment

- package.json
Viem requires Node 18+: https://viem.sh/docs/compatibility.html#platform-compatibility
We state that in engines section of package.json
> Add node >= 18 to engines in package.json

- src/entities/index.ts
- src/entities/nestedExit/doQueryNestedExit.ts
- src/entities/nestedExit/getNestedExitCalls.ts
- src/entities/nestedExit/getPeekCalls.ts
- src/entities/nestedExit/index.ts
- src/entities/nestedExit/parseNestedExitCall.ts
- src/entities/nestedExit/types.ts
- src/entities/nestedJoin/getNestedJoinCalls.ts
- src/entities/nestedJoin/index.ts
- src/entities/types.ts
- src/utils/constants.ts
- test/nestedExit.integration.test.ts
- Add proportional nested exit
- Add single token nested exit
> Nested Exit

- test/fxPool.integration.test.ts
- test/gyro2Math.test.ts
- test/gyro2Pool.test.ts
- test/gyro3Pool.integration.test.ts
- test/gyro3Pool.test.ts
- test/gyroEMath.test.ts
- test/gyroEPool.test.ts
- test/gyroEV2Pool.integration.test.ts
- test/gyroEV2Pool.test.ts
- test/sor.test.ts
- test/subgraph.test.ts
- tsconfig.json
- vitest.config.ts
Adds [globals vitest setup](https://vitest.dev/config/#globals) so that test files do not need to explicitly import `describe, it, beforeEach` etc
> Use vitest globals setup

- pnpm-lock.yaml
- src/entities/nestedExit/validateInputs.ts
- src/entities/nestedJoin/validateInputs.ts
- src/entities/utils/constraintValidation.ts
- src/entities/utils/index.ts
- test/constraintValidation.test.ts
General rules:
* Can only join/exit with the main tokens
* Main tokens only supported to a max of 1 level of nesting
* Can still pure join with > 1 level 
* A main token can't be a token in > 1 pool
We can only do minimal validation without introducing complexity/data overhead that the API should be handling. 
e.g. We can't validate pool state without constructing it which would require more complexity and data.
So we assume pool state is correct.
> Constraint validations

- examples/exit/weighted.ts
- examples/join/weighted.ts
- src/entities/exit/types.ts
- src/entities/exit/weighted/validateInputs.ts
- src/entities/exit/weighted/weightedExit.ts
- src/entities/join/composable-stable/composableStableJoin.ts
- src/entities/join/types.ts
- src/entities/join/utils/validateInputs.ts
- src/entities/join/weighted/weightedJoin.ts
- src/entities/utils/getAmounts.ts
- src/types.ts
- test/composableStableJoin.integration.test.ts
- test/lib/utils/joinHelper.ts
- test/weightedExit.integration.test.ts
- test/weightedJoin.integration.test.ts
Currently join inputs have TokenAmount as amountsIn type, but this adds too much complexity for the user to properly build the input. This task aims to replace that with a struct with more basic types:
`
InputAmount: {
address: Address;
decimals: number;
rawAmount: bigint;
}
`
> Refactor Input amounts

- src/data/providers/balancer-api/modules/pool-state/index.ts
- test/balancerApi.test.ts
We are working on assumption that API will return BPT token in token list (as current SG does) It does not currently do this so we have to add it manually.
> Manually add BPT in CS API Provider

- examples/exitPool.ts
- examples/joinPool.ts
- src/entities/exit/composable-stable/composableStableExit.ts
- src/entities/exit/types.ts
- src/entities/exit/weighted/weightedExit.ts
- src/entities/join/composable-stable/composableStableJoin.ts
- src/entities/join/types.ts
- src/entities/join/weighted/weightedJoin.ts
- test/lib/utils/exitHelper.ts
- test/lib/utils/joinHelper.ts
Update Join/ExitBuildOutput to use TokenAmounts instead of bigints. This should make it more useful for consumer.
> Build call output token amounts

- .changeset/eight-beans-remember.md
- src/pathGraph/pathGraph.ts
When comparing multiple paths for a swap, if one pool in any path is throwing, eg: new Error('Swap amount exceeds the pool limit') - it makes the PathGraph.getCandidatePaths to fail for all the other paths. Handling the error allows to return the other paths.
> fix: Ignore throwing paths

- .changeset/angry-papayas-live.md
- src/entities/index.ts
We need `PriceImpactAmount` in the consumers to get the return type of `PriceImpact.addLiquidityUnbalanced` but I noticed that it was not exposed.
> chore: expose priceImpact amount from entities index

- .changeset/strong-pandas-tie.md
- package.json
- pnpm-lock.yaml
- src/entities/addLiquidity/addLiquidityV2/index.ts
- src/entities/inputValidator/inputValidator.ts
- src/entities/removeLiquidity/removeLiquidityV2/index.ts
- src/entities/swap.ts
- src/utils/index.ts
- Use explicit `lodash.clonedeep` import to fix error when integrating with v0.7.0 
- It also avoids the whole lodash package in dependencies 
- Minor DX improvements in pool type error handling
- Exposes `poolTypeMapper`
> chore: Explicit lodash.clonedeep import and small DX improvements

- .changeset/early-eels-fry.md
- src/data/providers/balancer-api/index.ts
- src/data/providers/balancer-api/modules/nested-pool-state/index.ts
It extracts `mapPoolToNestedPoolState` function from `NestedPools` class and exposes so that consumers can use it as a helper function.
> chore: expose mapPoolToNestedPoolState function

- .changeset/many-eyes-do.md
- src/utils/poolTypeMapper.ts
Fixes an issue when mapping pools of type `GYRO2` that have `GYRO` type (without trailing `2`) in the [schema generated from the API](https://github.com/balancer/frontend-v3/blob/c2356b6fa9eb2cb95457697f7332fc2fa81731d9/lib/shared/services/api/generated/graphql.ts#L905).
> fix: add GYRO type for GYRO2 in pool type mapper

- .changeset/hot-timers-tell.md
- src/data/providers/balancer-api/index.ts
- src/data/providers/balancer-api/modules/nested-pool-state/index.ts
- src/entities/utils/validateNestedPoolState.ts
API returns the BPT address as part of the nestedPool tokens data when pool has phantomBpt. (This is unexpected?)
When mapping it meant it appeared in `pools` twice. The change filters out any phantomBpt. 
Note - this only fixes things for consumers using sdk data providers, it may cause issues if API is being consumed/mapped separately.
```
{
"data": {
"poolGetPool": {
"poolTokens": [
{
"index": 0,
"address": "0x49cbd67651fbabce12d1df18499896ec87bef46f",
"decimals": 18,
"nestedPool": {
"id": "0x49cbd67651fbabce12d1df18499896ec87bef46f00000000000000000000064a",
"address": "0x49cbd67651fbabce12d1df18499896ec87bef46f",
"type": "COMPOSABLE_STABLE",
"tokens": [
{
"index": 0,
"address": "0x49cbd67651fbabce12d1df18499896ec87bef46f", ----------PhantomBpt token
"decimals": 18
},
{
"index": 1, …
```
> Fix nested phantom bpt

- .changeset/purple-points-perform.md
- src/entities/removeLiquidityNested/doRemoveLiquidityNestedQuery.ts
- src/entities/removeLiquidityNested/getPeekCalls.ts
- src/entities/removeLiquidityNested/index.ts
Closes #377 
Peek calls were being added at the end of the multicall array.
This is a problem because results are temporary and may be consumed/cleared by the time the peek happens.
In order to fix this, peek calls were moved to right after their respective call.
> Fix remove liquidity nested query (peek) logic

- .changeset/rare-goats-exercise.md
- src/entities/removeLiquidityNested/getQueryCallsAttributes.ts
OutputReference index was being incorrectly passed down to the next call input.
> Fix outputReference index being incorrectly consumed

- examples/addLiquidity/addLiquidity.ts
- src/data/providers/balancer-api/modules/pool-state/index.ts
- src/utils/constants.ts
This pr fixes the add-liquidity-example. The following changes were made:
- replace the api endpoint. Some V3 pools are not part of the production api endpoint. At a further point in time we need to change it back to the production endpoint
- Reduce add liquidity amount as otherwise the priceImpact calculation (swap queries) will revert with the pool used, due to `revert MaxAmountInRatio`
- Add the chain parameter to the api query
- Added chain name strings the api requires to constants. I initially tried accessing the `Chain.name` from https://github.com/wevm/viem/blob/main/src/types/chain.ts#L49. However, even with uppercasing them they do not perfectly match with what the api expects.
> fix: add liquidity example

- .changeset/sixty-squids-report.md
- examples/addLiquidity/addLiquidityCowAmm.ts
- src/data/providers/balancer-api/modules/pool-state/index.ts
- src/entities/addLiquidity/addLiquidityCowAmm/index.ts
- src/entities/utils/cowAmmHelpers.ts
- src/entities/utils/index.ts
Context: Add Liquidity Proportional Query for CowAmm pools rely on getting current pool state onChain and then calculating proportional amounts from it.
Existing calculateProportionalAmounts implementation was not matching the SC implementation for CowAmm pools, resulting in a few wei difference between them.
This PR adds a new calculateProportionalAmountsCowAmm that replicates exactly the math done in the SC, resulting in an exact match between their results.
> Fix add liquidity proportional query for cow-amm

- .changeset/tall-jokes-leave.md
- src/entities/utils/cowAmmHelpers.ts
- test/lib/utils/addresses.ts
Here’s a bit of context on what this PR fixes:
CowAmm pools use custom maths operations called `bdiv` and `bmul` to calculate proportional amounts internally. The problem is that they are not the exact opposite of each other. In other words, when using them: `a / b = c` but `c * b != a`
This is a problem because we get a referenceAmount (i.e. max user balance) to calculate bptOut and, from there, querying with bptOut as input won't return the same referenceAmount in.
Since these behave similar to `divUp` and `mulUp`, we end up with a slightly bigger amountIn than the user balance.I created a variation of those maths called `bdivDown` and `bmulDown` so we get a slightly smaller bptOut instead, from there we can then use bdiv and bmul to get an exact match on the query amounts.
This will …
> Fix calculate proportional amounts rounding direction for Cow Amm

- .changeset/green-pets-wait.md
- src/entities/addLiquidity/addLiquidityCowAmm/index.ts
- src/entities/addLiquidity/addLiquidityV2/composableStable/addLiquidityComposableStable.ts
- src/entities/addLiquidity/addLiquidityV2/index.ts
- src/entities/addLiquidity/addLiquidityV2/stable/addLiquidityStable.ts
- src/entities/addLiquidity/addLiquidityV2/weighted/addLiquidityWeighted.ts
- src/entities/addLiquidity/addLiquidityV3/index.ts
- src/entities/inputValidator/inputValidator.ts
- src/entities/removeLiquidity/removeLiquidityV3/index.ts
- src/entities/swap/index.ts
- src/utils/errors.ts
- test/entities/swaps/v3/swapV3.integration.test.ts
- test/v3/addLiquidity.integration.test.ts
Closes #383
Functionality was added to SC implementation and required updating Input Validator and Integration tests.
Closes #351
Took the opportunity and re-enabled swap tests
Extra:
Fix lint issues regarding missing buildCallWithPermit implementations
> Accept ETH as input on buildCallWithPermit

- .changeset/gentle-months-share.md
- .github/workflows/checks.yml
- test/anvil/anvil-global-setup.ts
- vitest.config.mts
Fixes integration tests by: 
1. Replacing optimism fallback rpc url from `https://optimism.gateway.tenderly.co` (was failing) to `https://optimism.llamarpc.com` (more stable according to `https://chainlist.org/chain/10`) 
2. Defining `OPTIMISM_RPC_URL` in CI and vitest setup. 
The last step would be defining the `OPTIMISM_RPC_URL` env in the repo secrets.
> chore: add optimism rpc url to envs

- .changeset/selfish-baboons-sort.md
- pnpm-lock.yaml
- src/entities/permit2Helper/index.ts
- src/entities/permitHelper/helper.ts
- src/entities/permitHelper/index.ts
- src/entities/relayer/authorization.ts
- src/entities/relayer/index.ts
- src/utils/index.ts
- src/utils/types.ts
- test/entities/swaps/v2/swapV2.integration.test.ts
- test/entities/swaps/v3/swapV3.integration.test.ts
- test/lib/utils/helper.ts
- test/lib/utils/swapHelpers.ts
- test/lib/utils/types.ts
- test/v2/addLiquidityNested/addLiquidityNested.integration.test.ts
- test/v2/addLiquidityNested/addLiquidityNestedPolygon.integration.test.ts
- test/v2/removeLiquidityNested/removeLiquidityNested.integration.test.ts
- test/v2/utils/calculateProportionalAmounts.integration.test.ts
- test/v3/addLiquidity.integration.test.ts
- test/v3/removeLiquidity.integration.test.ts
As a consumer, I want to have access to the type of the `client` parameter when calling methods like: 
`Relayer.signRelayerApproval` or `Permit2Helper.signAddLiquidityApproval` 
This PR refactors internal usages and exposes type:
```TS
export type ViemClient = Client & WalletActions & PublicActions;
```
> Viem client type

- .changeset/nasty-phones-care.md
- src/entities/addLiquidityNested/doAddLiquidityNestedQuery.ts
- src/entities/removeLiquidityNested/doRemoveLiquidityNestedQuery.ts
- src/entities/swap/swaps/v2/auraBalSwaps/joinSwap.ts
- src/entities/swap/swaps/v2/auraBalSwaps/swapExit.ts
- src/utils/constants.ts
We found an issue with different RPC providers and the only solution is using `ZERO_ADDRESS` as the default account in certain multicall viem calls. 
More context: 
https://github.com/wevm/viem/issues/2792
> fix: Add zero address sender to viem multicall calls to avoid issues with Nethermind/Geth nodes

- .changeset/unlucky-mangos-doubt.md
- src/entities/addLiquidity/addLiquidityV3/doAddLiquidityProportionalQuery.ts
- src/entities/addLiquidity/addLiquidityV3/doAddLiquiditySingleTokenQuery.ts
- src/entities/addLiquidity/addLiquidityV3/doAddLiquidityUnbalancedQuery.ts
- src/entities/addLiquidity/addLiquidityV3/index.ts
- src/entities/addLiquidity/index.ts
- src/entities/addLiquidity/types.ts
- src/entities/addLiquidityBoosted/index.ts
- src/entities/addLiquidityBoosted/types.ts
- src/entities/removeLiquidity/index.ts
- src/entities/removeLiquidity/removeLiquidityV3/doRemoveLiquidityProportionalQuery.ts
- src/entities/removeLiquidity/removeLiquidityV3/doRemoveLiquiditySingleTokenExactInQuery.ts
- src/entities/removeLiquidity/removeLiquidityV3/doRemoveLiquiditySingleTokenExactOutQuery.ts
- src/entities/removeLiquidity/removeLiquidityV3/encodeRemoveLiquidityProportional.ts
- src/entities/removeLiquidity/removeLiquidityV3/encodeRemoveLiquiditySingleTokenExactIn.ts
- src/entities/removeLiquidity/removeLiquidityV3/encodeRemoveLiquiditySingleTokenExactOut.ts
- src/entities/removeLiquidity/removeLiquidityV3/index.ts
- src/entities/removeLiquidity/types.ts
- src/entities/removeLiquidityBoosted/index.ts
- src/entities/removeLiquidityBoosted/types.ts
- src/entities/swap/index.ts
- src/entities/swap/swaps/types.ts
- src/entities/swap/swaps/v3/index.ts
- test/lib/utils/addLiquidityHelper.ts
- test/lib/utils/removeLiquidityHelper.ts
- test/lib/utils/removeLiquidityRecoveryHelper.ts
- test/v3/removeLiquidityBoosted/removeLiquidityBoosted.integration.test.ts
> 438 update to allow optional address for addremoveswap

- .changeset/sour-bears-sin.md
- src/data/providers/balancer-api/modules/nested-pool-state/index.ts
- src/data/types.ts
- src/entities/priceImpact/addLiquidityNested.ts
- src/entities/priceImpact/addLiquidityUnbalancedBoosted.ts
- src/entities/priceImpact/index.ts
- src/entities/types.ts
- src/entities/utils/isPoolToken.ts
- src/entities/utils/validateNestedPoolState.ts
- test/mockData/boostedPool.ts
- test/mockData/nestedPool.ts
- test/mockData/partialBoostedPool.ts
- test/nestedPoolStateValidation.test.ts
- test/v3/addLiquidityNested/addLiquidityNestedV3.integration.test.ts
- test/v3/addLiquidityNested/addLiquidityNestedV3Signature.integration.test.ts
- test/v3/priceImpact/priceImpact.V3.integration.test.ts
- test/v3/removeLiquidityNested/removeLiquidityNestedV3.integration.test.ts
- test/v3/removeLiquidityNested/removeLiquidityNestedV3Signature.integration.test.ts
Also refactors nested add/remove to have different pool state for V2/V3. V3 use a new poolState requiring tokens with underlying info:
```
export type PoolTokenWithUnderlying = MinimalToken & {
underlyingToken: MinimalToken | null;
};
type NestedPoolBase = {
id: Hex;
address: Address;
type: PoolType;
level: number; // 0 is the bottom and the highest level is the top
};
export type NestedPoolV2 = NestedPoolBase & {
tokens: MinimalToken[]; // each token should have at least one
};
export type NestedPoolV3 = NestedPoolBase & {
tokens: PoolTokenWithUnderlying[]; // each token should have at least one
};
type NestedPoolStateBase = {
protocolVersion: 1 | 2 | 3;
mainTokens: {
address: Address;
decimals: number;
}[];
};
export type NestedPoolStateV2 = NestedPoolStateBase & {
protocolVersion: 1 | …
```
> V3 price impact for nested pools

- .changeset/tricky-points-smell.md
- src/entities/utils/isPoolToken.ts
- src/entities/utils/validateNestedPoolState.test.ts
Using `mapPoolToNestedPoolStateV2` with an V2 pool such as:
```
id: '0x08775ccb6674d6bdceb0797c364c2653ed84f3840002000000000000000004f0',
address: '0x08775ccb6674d6bdceb0797c364c2653ed84f384',
```
returns something like: 
```
[
{
"address": "0x08775ccb6674d6bdceb0797c364c2653ed84f384",
"id": "0x08775ccb6674d6bdceb0797c364c2653ed84f3840002000000000000000004f0",
"level": 1,
"tokens": [
{
"address": "0x79c58f70905f734641735bc61e45c19dd9ad60bc",
"decimals": 18,
"index": 0,
"underlyingToken": null,
},
{
"address": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
"decimals": 18,
"index": 1,
"underlyingToken": null,
},
],
"type": "Weighted",
},
{
"address": "0x79c58f70905f734641735bc61e45c19dd9ad60bc",
"id": "0x79c58f70905f734641735bc61e45c19dd9ad60bc0000000000000000000004e7",
"level": 0,
"tokens": …
```
> fix: nested single token remove v2 validation

- .changeset/fuzzy-coins-sin.md
- src/data/providers/balancer-api/modules/nested-pool-state/index.ts
> Refactor nestedPoolState logic to fetch mainTokens from api

- .changeset/chilled-hornets-explode.md
- src/entities/utils/getPoolStateWithBalancesV2.ts
We are hitting this error quite frequently from our integration tests in GHA. 
This PR adds a console.log to debug the issue.
> chore: log multicall v2 pool state error

- .changeset/chilled-phones-explain.md
- src/entities/priceImpact/addLiquidityUnbalancedBoosted.ts
- test/anvil/anvil-global-setup.ts
- test/lib/utils/addLiquidityHelper.ts
- test/mockData/partialBoostedPool.ts
- test/v3/priceImpact/priceImpact.V3.integration.test.ts
Close #525 
Main:
- Move try/catch handler to inner Price Impact function so it covers other places where it's used
Other:
- Bump sepolia global blockNumber
- Remove hardcoded amounts from Price Impact integration tests (we'll need to find a better approach)
> Fix price impact with near proportional inputs for AddLiquidityNested

- .changeset/wild-paws-whisper.md
- test/lib/utils/addLiquidityHelper.ts
- test/v2/addLiquidity/gyro2.integration.test.ts
- test/v2/addLiquidity/gyro3.integration.test.ts
- test/v2/addLiquidity/gyroE.integration.test.ts
- test/v2/addLiquidity/gyroEV2.integration.test.ts
- test/v2/removeLiquidity/gyro2.integration.test.ts
- test/v2/removeLiquidity/gyro3.integration.test.ts
- test/v2/removeLiquidity/gyroE.integration.test.ts
- test/v2/removeLiquidity/gyroEV2.integration.test.ts
Main changes:
- Add extra integration tests for add liquidity proportional with referenceAmount (non-bpt) for gyro pools.
Other than that, I took the opportunity to fix some lint warnings we had on missing custom errors that were hanging around for a while and for some reason weren't being properly flagged by the linter.
> Add extra integration tests for gyro pools

- .changeset/silly-dolls-matter.md
- examples/removeLiquidity/removeLiquidityRecovery.ts
- src/entities/removeLiquidity/index.ts
- src/entities/removeLiquidity/removeLiquidityCowAmm/index.ts
- src/entities/removeLiquidity/removeLiquidityV2/composableStable/removeLiquidityComposableStable.ts
- src/entities/removeLiquidity/removeLiquidityV2/index.ts
- src/entities/removeLiquidity/removeLiquidityV2/stable/removeLiquidityStable.ts
- src/entities/removeLiquidity/removeLiquidityV2/weighted/removeLiquidityWeighted.ts
- src/entities/removeLiquidity/removeLiquidityV3/index.ts
- src/entities/removeLiquidity/types.ts
- src/entities/removeLiquidityBoosted/index.ts
- test/lib/utils/removeLiquidityRecoveryHelper.ts
Closes #531 
-- IMPORTANT --
Please note that this bumps a `major version` as it's a breaking change to the external interface.
I think that should be ok as we're preparing to release v1.0
> Remove duplicate queryRemoveLiquidityRecovery

- .changeset/hungry-dragons-compare.md
- test/entities/swaps/v3/swapV3.integration.test.ts
- test/lib/utils/addresses.ts
> Refactor swaps v3 integration tests

- src/utils/constants.ts
Simulations are failing in sonic cause multicall3 address is not yet defined in viem.
This is a temporary workaround until the viem/wagmi team releases a version fixing it.
> fix: override multicall3 for sonic in viem chain definition

- .changeset/two-ants-act.md
- examples/createAndInitPool/createAndInitPoolV3.ts
- src/entities/initPool/index.ts
- src/entities/initPool/initPoolV3.ts
- src/entities/permit2Helper/index.ts
- test/v3/createPool/stable/stable.integration.test.ts
- test/v3/createPool/weighted/weighted.integration.test.ts
Closes #476 
- For testing, we could modify [doInitPool](https://github.com/balancer/b-sdk/blob/74d61ab3476134b2406bc14f33e81b8e83752798/test/lib/utils/initPoolHelper.ts#L23-L46)  to handle both v2 and v3, but I'm proposing we favor the more straightforward approach
- Refactored pool creation example to offer functions for both fork and live network
- Refactored `getDetails` of `Permit2Helper` to allow for type `Account` so that `client.signTypedData` can be run with a script
> Add permit2 for init pool

- .changeset/silver-eels-peel.md
- src/entities/utils/getPoolStateWithBalancesV3.ts
- test/anvil/anvil-global-setup.ts
- test/lib/utils/addresses.ts
- test/mockData/boostedPool.ts
- test/v3/addLiquidity/addLiquidity.integration-gnosis.test.ts
Closes #561 
getPoolStateWithBalances should use raw balances instead of live balances when used to calculate proportional amounts
this PR fixes an issue where karpatkey is trying to add liquidity to the [sDAI/BRLA pool](https://balancer.fi/pools/gnosis/v3/0xa91c3c043051e7e680b61d79b3a733d3e2c0fb5e) on gnosis chain
> Fix getPoolStateWithBalancesV3 helper

- src/entities/inputValidator/gyro/inputValidatorGyro.ts
- test/v3/createPool/gyroECLP/gyroECLP.validation.test.ts
- Use SDKError `message` to differentiate between base vs derived param validations
- Use error message thrown by [balancer maths](https://github.com/balancer/balancer-maths/blob/0dcd1db8f8efb1e150787dd2c60274c461f0fc12/typescript/src/gyro/gyroECLPMath.ts#L80-L109) as the SDKError `suggestion`
> Refactor errors thrown by ECLP param validations 

- .changeset/kind-schools-exist.md
- .github/actions/setup/action.yml
Install check started failing "out of the blue" after attempting to do a release
1. [This PR](https://github.com/balancer/b-sdk/pull/634) was merged w/ install check passing
2. [Release PR](https://github.com/balancer/b-sdk/pull/637) was merged
3. Install check [starts failing](https://github.com/balancer/b-sdk/actions/runs/14200966111/job/39789229064) which blocks new release
- Moved install of dependencies before attempting to cache `node_modules`
> Fix Install check

- .github/actions/setup/action.yml
Closes #639 
Per @johngrantuk 
> Looks like npm had an outage yesterday which might be the reason: https://status.npmjs.org/
- Moved install after cache lookup for node_modules
> Cache node_modules before install

- .changeset/hungry-rocks-jam.md
- src/data/providers/balancer-api/modules/boosted-pool-state/index.ts
- src/data/providers/balancer-api/modules/nested-pool-state/index.ts
- src/data/providers/balancer-api/modules/pool-state/index.ts
- src/entities/addLiquidityNested/addLiquidityNestedV2/index.ts
- src/entities/removeLiquidityNested/removeLiquidityNestedV2/index.ts
- src/entities/types.ts
- src/utils/helpers.ts
V3 does not need a specific pool type for add/removes/swaps to work. We were using `mapPoolType` in API provider which would throw if we don't manually add each new type to supported types. I've changed it to just use the type passed (as string) whenever its V3.
> Fix map pool type

- .changeset/every-snails-wear.md
- package.json
- src/utils/calculateReClammInitAmounts.ts
Not sure this is the best way to remove the circular dependency, but I couldn't find a better/easier way to do it 😅 
Feel free to suggest a better approach 🙃
> Fix ReClamm init lint issues

- .changeset/five-chicken-strive.md
- src/utils/constants.ts
FE throwing this error when trying to build call for init pool on hyperEVM with `wethIsEth` set to `true`
```
Cannot read properties of undefined (reading 'wrapped')
```
I think is thrown by `isSameAddress` because we are missing native asset config for hyperEVM 
https://github.com/balancer/b-sdk/blob/96d8262109aa4b3561d3970f61ac7d01f34bf6b0/src/entities/inputValidator/inputValidatorBase.ts#L52-L68
> Add hyperEVM native asset config
