.changeset/slimy-tomatoes-shave.md
src/data/providers/subgraphPoolProvider.ts
src/data/types.ts
src/entities/pools/fx/fxFactory.ts
src/entities/pools/fx/fxMath.ts
src/entities/pools/fx/fxPool.ts
src/entities/pools/fx/helpers.ts
src/entities/pools/fx/index.ts
src/entities/pools/parser.ts
src/types.ts
test/fxPool.integration.test.ts
test/fxPool.test.ts
test/lib/testData/fxPool_43667355.json

Main:
- Add FX pool based on SOR implementation.

Add FX pool

---

.changeset/proud-penguins-type.md
.github/workflows/checks.yml
.github/workflows/main.yml
jest.config.js
package.json
pnpm-lock.yaml
test/fxPool.integration.test.ts
test/fxPool.test.ts
test/gyro2Math.test.ts
test/gyro2Pool.test.ts
test/gyro3Pool.integration.test.ts
test/gyro3Pool.test.ts
test/gyroEMath.test.ts
test/gyroEPool.test.ts
test/gyroEV2Pool.integration.test.ts
test/gyroEV2Pool.test.ts
test/sor.test.ts
test/subgraph.test.ts

- jest -> vitest
- bump viem
- pnpm v8

Switch to vitest

---

src/entities/join/weighted/weightedJoin.ts
src/entities/utils/parseJoinArgs.ts
test/weightedExit.integration.test.ts
test/weightedJoin.integration.test.ts

* Refactor join/exit tests to make it easier to follow
* Fix native asset test on join
* Fix native asset handling on join

Refactor tests

---

.changeset/eleven-trains-kneel.md
.github/workflows/checks.yml
debug/multicall.ts
src/data/enrichers/onChainPoolDataEnricher.ts
src/data/onChainPoolDataViaReadContract.ts
src/data/providers/subgraphPoolProvider.ts
src/entities/swap.ts
src/sor.ts
src/utils/constants.ts
test/fxPool.integration.test.ts
test/gyroEV2Pool.integration.test.ts
test/sor.test.ts
test/subgraph.test.ts

Note - Needs FANTOM_RPC_URL added to .env/CI for tests to run.

Fantom config

---

.changeset/sour-turkeys-notice.md
src/utils/constants.ts

add OP native asset, remove unused

---

package.json
pnpm-lock.yaml
src/data/onChainPoolDataViaReadContract.ts
src/entities/addLiquidity/index.ts
src/entities/encoders/composableStable.ts
src/entities/encoders/weighted.ts
src/entities/index.ts
src/entities/inputValidator/composableStable/inputValidatorComposableStable.ts
src/entities/inputValidator/gyro/inputValidatorGyro.ts
src/entities/inputValidator/inputValidator.ts
src/entities/inputValidator/types.ts
src/entities/inputValidator/utils/validateTokens.ts
src/entities/priceImpact/index.ts
src/entities/removeLiquidity/index.ts

Removes all 8 circular dependencies(Not considering type imports);

Adds "dpdm" package to detect circular dependencies;

---

.changeset/metal-kings-explain.md
src/sor.ts
src/static.ts

solves https://github.com/balancer/b-sdk/issues/188

check length of candidate paths

---

.changeset/many-wolves-learn.md
test/lib/utils/addresses.ts
test/v2/removeLiquidity/composableStable.recovery.integration.test.ts

200 recovery exits v2

---

examples/utils/calculateProportionalAmounts.ts
src/data/providers/balancer-api/modules/pool-state/index.ts
src/entities/types.ts
src/entities/utils/calculateProportionalAmounts.ts
test/v2/utils/calculateProportionalAmounts.integration.test.ts

Changing example pool to Gyroscope ECLP wstETH/wETH;

Adding bptOut to the calculation of the proportional amounts;

---

.changeset/gold-tips-attend.md
src/data/providers/balancer-api/modules/pool-state/index.ts
src/entities/addLiquidity/addLiquidityV2/composableStable/addLiquidityComposableStable.ts
src/entities/addLiquidity/addLiquidityV2/index.ts
src/entities/addLiquidity/addLiquidityV2/stable/addLiquidityStable.ts
src/entities/addLiquidity/addLiquidityV2/weighted/addLiquidityWeighted.ts
src/entities/addLiquidity/helpers.ts
src/entities/encoders/stable.ts
src/entities/inputValidator/inputValidator.ts
src/entities/inputValidator/stable/inputValidatorStable.ts
src/entities/removeLiquidity/helper.ts
src/entities/removeLiquidity/removeLiquidityV2/composableStable/removeLiquidityComposableStable.ts
src/entities/removeLiquidity/removeLiquidityV2/index.ts
src/entities/removeLiquidity/removeLiquidityV2/stable/removeLiquidityStable.ts
src/entities/types.ts
src/types.ts
src/utils/errors.ts
src/utils/helpers.ts
src/utils/poolTypeMapper.ts
test/anvil/anvil-global-setup.ts
test/lib/utils/addresses.ts
test/v2/addLiquidity/stable.integration.test.ts
test/v2/removeLiquidity/stable.integration.test.ts

Add add/remove liquidity support for Stable and Metastable Pools

---

README.md

Updated readme. Idea is this API type documentation will be kept up to date as part of any future PRs and serves as the source to be copied to docs reference page. Also added some missing info for local setup and links to relevant examples.

refactor: Update readme.

---

.changeset/strange-ears-return.md
examples/addLiquidity/addLiquidity.ts
examples/addLiquidity/addLiquidityNested.ts
examples/createAndInitPool/createAndInitPool.ts
examples/lib/makeForkTx.ts
examples/removeLiquidity/removeLiquidity.ts
examples/removeLiquidity/removeLiquidityNested.ts
examples/removeLiquidity/removeLiquidityRecovery.ts
src/data/providers/balancer-api/modules/pool-state/index.ts

Main important fix here is the BalancerApi to handle non-lowercase address/id.

Example fixes

---

examples/addLiquidity/addLiquidity.ts
examples/addLiquidity/addLiquidityNested.ts
examples/priceImpact/addLiquidity.ts
examples/removeLiquidity/removeLiquidity.ts
examples/removeLiquidity/removeLiquidityNested.ts
examples/removeLiquidity/removeLiquidityRecovery.ts
examples/swaps/swap.ts
examples/utils/calculateProportionalAmounts.ts
src/utils/constants.ts
test/v2/data/balancerApi.test.ts

This pr replaces the hardcoded api endpoints and introduces it as an exported constant. Closes #361

chore: change api endpoint

---

.changeset/tame-monkeys-scream.md

add changeset

---

.changeset/pretty-pets-repair.md

Add changeset for previous merge of update to deploy8

---

.changeset/smooth-badgers-battle.md
examples/swaps/swap.ts
src/entities/swap/swaps/v3/index.ts
src/entities/swap/types.ts

adds support for v3 swaps to optionally pass a `userData` value

Support userdata for v3 swaps

---

.changeset/tasty-buses-tickle.md
src/entities/swap/index.ts

462 expose isbatchswap on swap class

---

.changeset/pink-phones-suffer.md
src/entities/utils/getPoolStateWithBalancesV3.ts
test/v3/utils/getPoolStateWithBalancesV3.integration.test.ts

Fix getPoolStateWithBalancesV3 with less 18 decimals tokens

---

.changeset/dry-bananas-tan.md
src/entities/inputValidator/stable/inputValidatorStable.ts
test/anvil/anvil-global-setup.ts
test/lib/utils/addLiquidityHelper.ts
test/lib/utils/addresses.ts
test/v3/addLiquidity/addLiquidity.stable.integration.test.ts
test/v3/priceImpact/priceImpact.V3.integration.test.ts

Enable add liquidity proportional for stable pools on v3

---

.changeset/hungry-roses-sleep.md
src/entities/addLiquidityBuffer/index.ts
src/entities/index.ts
src/entities/initBuffer/doInitBufferQuery.ts
src/entities/initBuffer/index.ts
src/entities/initBuffer/types.ts
src/entities/permit2Helper/index.ts
src/entities/tokenAmount.ts
test/anvil/anvil-global-setup.ts
test/lib/utils/addresses.ts
test/v2/addLiquidity/stable.integration.test.ts
test/v2/createPool/composableStable.integration.test.ts
test/v2/initPool/composableStable.integration.test.ts
test/v2/removeLiquidity/composableStable.integration.test.ts
test/v2/removeLiquidity/weighted.integration.test.ts
test/v3/initBuffer/initBuffer.integration.test.ts

Add support for InitBuffer

---

.changeset/tame-trains-greet.md
src/entities/addLiquidity/addLiquidityCowAmm/index.ts
src/entities/addLiquidity/addLiquidityV3/doAddLiquidityProportionalQuery.ts
src/entities/addLiquidity/addLiquidityV3/doAddLiquiditySingleTokenQuery.ts
src/entities/addLiquidity/addLiquidityV3/doAddLiquidityUnbalancedQuery.ts
src/entities/addLiquidity/addLiquidityV3/index.ts
src/entities/addLiquidity/index.ts
src/entities/addLiquidity/types.ts
src/entities/addLiquidityBoosted/doAddLiquidityPropotionalQuery.ts
src/entities/addLiquidityBoosted/doAddLiquidityUnbalancedQuery.ts
src/entities/addLiquidityBoosted/index.ts
src/entities/addLiquidityBuffer/doAddLiquidityQuery.ts
src/entities/addLiquidityBuffer/index.ts
src/entities/addLiquidityNested/addLiquidityNestedV3/index.ts
src/entities/addLiquidityNested/index.ts
src/entities/removeLiquidity/index.ts
src/entities/removeLiquidity/removeLiquidityCowAmm/index.ts
src/entities/removeLiquidity/removeLiquidityV3/doRemoveLiquidityProportionalQuery.ts
src/entities/removeLiquidity/removeLiquidityV3/doRemoveLiquidityRecoveryQuery.ts
src/entities/removeLiquidity/removeLiquidityV3/doRemoveLiquiditySingleTokenExactInQuery.ts
src/entities/removeLiquidity/removeLiquidityV3/doRemoveLiquiditySingleTokenExactOutQuery.ts
src/entities/removeLiquidity/removeLiquidityV3/index.ts
src/entities/removeLiquidity/types.ts
src/entities/removeLiquidityBoosted/doRemoveLiquidityProportionalQuery.ts
src/entities/removeLiquidityBoosted/index.ts
src/entities/removeLiquidityNested/index.ts
src/entities/removeLiquidityNested/removeLiquidityNestedV3/index.ts
src/entities/utils/cowAmmHelpers.ts

- Will use in Balancer Maths tests
- Haven't added to V2 as never been requested and would require a large amount of changes, IMO not worth the effort.

Add query blockno param for add/remove liq 

---

src/abi/index.ts

in general i think exporting all abis from SDK is nice so devs can easily import source of truth for parsing event logs

Export stable surge factory abi

---

.changeset/funny-spiders-argue.md
.github/workflows/checks.yml
examples/swaps/swapV2.ts
package.json
src/entities/addLiquidityNested/addLiquidityNestedV2/getQueryCallsAttributes.ts
src/entities/removeLiquidity/helper.ts
src/entities/removeLiquidityNested/removeLiquidityNestedV2/getQueryCallsAttributes.ts
test/entities/swaps/swap.test.ts
test/lib/utils/addLiquidityHelper.ts
test/lib/utils/relayerHelper.ts
test/lib/utils/types.ts
test/v3/removeLiquidityBoosted/removeLiquidityBoosted.integration.test.ts

Closes #611
- Added type checking to CI 
- Biome only does linting and formatting
- Split steps for better DX

chore: improve code quality checks

---

.changeset/dull-ducks-juggle.md
src/entities/priceImpact/addLiquidityUnbalanced.ts
src/entities/priceImpact/addLiquidityUnbalancedBoosted.ts
src/entities/priceImpact/index.ts

Refactor price impact errors as SDKError

---

test/entities/swaps/v2/swapV2.integration.test.ts

Closes #645 
Main changes:
The assumption is that sequential tests may have been conflicting with each other based on the fact that they run in parallel and reuse the same fork node.
In order to fix that it was applied the pattern from other working tests, where the fork setup happens only once and then each test restarts it from a snapshot.
Extra changes:
- In order to avoid the need to fix the blockNumber, tests comparing against hardcoded amounts were removed. Since they were checking against query results, they were considered redundant when compared to tests checking actual transaction results.
Ps: no changeset needed since this test fix does not require a package release

Attempt to fix swap v2 integration test failing on CI

---

.changeset/small-forks-enjoy.md
src/utils/customChains.ts

also remove slashes at the end of urls

chore: update hyperevm block explorer
